### ISSUE TITLE
p4sde not be compiled

### ISSUE THREAD

**Issue by qzhan16** [ipdk-io/ipdk#174]
reproduce this at commit 45e163a5413e7da6

Seems the script build_p4sde.sh needs minor change as below, otherwise, p4sde will not be built.

diff --git a/build/networking/scripts/build_p4sde.sh b/build/networking/scripts/build_p4sde.sh
index 5b5f875..90e7a69 100755
--- a/build/networking/scripts/build_p4sde.sh
+++ b/build/networking/scripts/build_p4sde.sh
@@ -63,7 +63,7 @@ cd p4-driver
git checkout 780b3dfa205815e87f4580383cc37bfa30187f7c

pip3 install distro
-cd p4-driver/tools/setup
+cd tools/setup
if [ "${OS}" = "Ubuntu" ]; then
     echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
fi

**Comment by mestery** [comment]
Hi @qzhan16, thanks for reporting this issue. Can you file a PR, following the [contributing guidelines](https://github.com/ipdk-io/ipdk/blob/main/CONTRIBUTING.md)? Also, instead of using `cd` above, it would be better to use appropriate `pushd` and `popd` rather than assuming you are in a specific directory.

**Comment by qzhan16** [comment]
Hi @mestery , the pull request has been created https://github.com/ipdk-io/ipdk/pull/176

**Comment by vsureshkumarp** [comment]
Closing the issue as it is already addressed by @qzhan16 with PR #176
